Repository milvus-io/birdwatcher, pull requests merged in 2022-09, with the labels that each got.

#22 Add cmd for show querycoord cluster info
  models/session.go
  states/querycoord_cluster.go
  states/show.go
  states/show_querycoord_task.go
  states/show_session.go
  states/util.go
Labels: approved, dco-passed, lgtm, size/L

#23 Print querycoord task in accending order
  states/querycoord_task.go
  states/show_querycoord_task.go
Labels: approved, dco-passed, lgtm, size/L

#25 Fix print start position instead of dml position
  states/show_segment.go
Labels: kind/bug, approved, dco-passed, lgtm, size/XS

#28 Add dry mode to select milvus instance
  states/backup_mock_connect.go
  states/etcd_connect.go
  states/exit.go
  states/garbage_collect.go
  states/instance.go
  states/states.go
  states/util.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/L

#31 Adapt go 1.18
  .github/workflows/golangci-lint.yml
  README.md
  go.mod
  go.sum
  states/querycoord_task.go
  states/show.go
  states/update_log_level.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#30 Add show segment-index command
  states/backup_mock_connect.go
  states/etcd_restore.go
  states/show.go
  states/show_index.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/L

#32 Add cmd for showing channel related meta info
  states/querycoord_channels.go
  states/show.go
  states/show_querycoord_task.go
  states/util.go
Labels: approved, dco-passed, lgtm, size/L

#33 Add cmd for showing loaded collections
  states/querycoord_channels.go
  states/show.go
  states/show_collection_load.go
  states/util.go
Labels: approved, dco-passed, lgtm, size/L

#36 Adapt segment binlog v2.2 format
  states/show_segment.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/M

#37 Sort segment by id
  states/show_segment.go
Labels: approved, dco-passed, lgtm, size/XS

#39 Add SetupCommands for each state and call it after exec
  states/backup_mock_connect.go
  states/etcd_connect.go
  states/exit.go
  states/instance.go
  states/states.go
  states/visit_datacoord.go
  states/visit_datanode.go
  states/visit_indexcoord.go
  states/visit_indexnode.go
  states/visit_querycoord.go
  states/visit_querynode.go
  states/visit_rootcoord.go
Labels: kind/bug, approved, dco-passed, lgtm, size/L

#42 Add multi-level command suggestion
  go.mod
  go.sum
  main.go
  states/cmd.go
  states/states.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#43 Enable output all segment's indexes
  states/show_index.go
Labels: approved, dco-passed, lgtm, size/S
