Repository milvus-io/birdwatcher, pull requests merged in 2022-10, with the labels that each got.

#45 Add command for release dropped collection
  states/force_release.go
  states/instance.go
  states/show_collection.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/M

#46 Remove segments and channels after release dropped collection
  states/force_release.go
  states/show_collection_load.go
Labels: kind/bug, approved, dco-passed, lgtm, size/M

#47 Fix remove delta Channel prefix
  states/force_release.go
Labels: kind/bug, approved, dco-passed, lgtm, size/XS

#48 Fix ineffectual assignment err lint issue
  states/force_release.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XS

#51 Adapt segment index info for v2.2
  asap/init.go
  main.go
  proto/v2.2/common.proto
  proto/v2.2/commonpb/common.pb.go
  proto/v2.2/data_coord.proto
  proto/v2.2/datapb/data_coord.pb.go
  proto/v2.2/etcd_meta.proto
  proto/v2.2/etcdpb/etcd_meta.pb.go
  proto/v2.2/gen_proto.sh
  proto/v2.2/index_cgo_msg.proto
  proto/v2.2/index_coord.proto
  proto/v2.2/indexpb/index_coord.pb.go
  proto/v2.2/internal.proto
  proto/v2.2/internalpb/internal.pb.go
  proto/v2.2/milvus.proto
  proto/v2.2/milvuspb/milvus.pb.go
  proto/v2.2/plan.proto
  proto/v2.2/proxy.proto
  proto/v2.2/proxypb/proxy.pb.go
  proto/v2.2/query_coord.proto
  proto/v2.2/querypb/query_coord.pb.go
  proto/v2.2/root_coord.proto
  proto/v2.2/rootcoordpb/root_coord.pb.go
  proto/v2.2/schema.proto
  proto/v2.2/schemapb/schema.pb.go
  proto/v2.2/segcore.proto
  states/show_index.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/XXL

#49 Add auto-complete for flags and file path
  go.mod
  go.sum
  main.go
  states/auto_complete.go
  states/auto_complete_file.go
  states/backup_mock_connect.go
  states/cmd.go
  states/states.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#55 fix force release
  states/force_release.go
Labels: approved, dco-passed, lgtm, size/XS

#54 Add repair v2.1 segment command
  states/download_segment.go
  states/instance.go
  states/repair_segment.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#56 Improve show index output
  models/session.go
  states/show.go
  states/show_channel_watch.go
  states/show_index.go
  states/show_segment.go
  states/util.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#57 Support remove segment by id, not only empty segment
  states/backup_mock_connect.go
  states/instance.go
  states/show_segment.go
Labels: approved, dco-passed, lgtm, size/M

#59 Fix checkpoint calculation not excluding dropped segment
  states/show_segment.go
Labels: kind/bug, approved, dco-passed, lgtm, size/XS

#61 Accept PAGER env to redirect long output
  main.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/M
