Repository milvus-io/birdwatcher, pull requests merged in 2022-12, with the labels that each got.

#66 Support reset cp to latest msgID or latest cp of pchannel
  Makefile
  go.mod
  go.sum
  mq/factory.go
  mq/ifc/id.go
  mq/ifc/message.go
  mq/ifc/msgstream.go
  mq/kafka/kafka.go
  mq/kafka/kafka_id.go
  mq/kafka/kafka_message.go
  mq/kafka/kafka_test.go
  mq/msg.go
  mq/pulsar/pulsar_id.go
  mq/pulsar/pulsar_message.go
  mq/pulsar/puslar.go
  mq/pulsar/puslar_test.go
  mq/unmarshal.go
  mq/utils.go
  states/instance.go
  states/reset_checkpoint.go
  states/show_collection.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XXL

#67 Add milvus v2.2 collection loaded function
  proto/v2.2/common.proto
  proto/v2.2/commonpb/common.pb.go
  proto/v2.2/data_coord.proto
  proto/v2.2/datapb/data_coord.pb.go
  proto/v2.2/etcd_meta.proto
  proto/v2.2/etcdpb/etcd_meta.pb.go
  proto/v2.2/index_coord.proto
  proto/v2.2/indexpb/index_coord.pb.go
  proto/v2.2/milvus.proto
  proto/v2.2/milvuspb/milvus.pb.go
  proto/v2.2/query_coord.proto
  proto/v2.2/querypb/query_coord.pb.go
  proto/v2.2/root_coord.proto
  proto/v2.2/rootcoordpb/root_coord.pb.go
  proto/v2.2/schema.proto
  proto/v2.2/schemapb/schema.pb.go
  states/show_collection.go
  states/show_collection_load.go
  states/show_querycoord_task.go
  states/show_segment.go
  states/visit_querynode.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XXL

#68 Fix go.mod not able to install
  go.mod
  go.sum
Labels: kind/bug, approved, dco-passed, lgtm, size/M

#70 Fill Milvus2.2 segment binlog lazy
  states/download_pk.go
  states/download_segment.go
  states/garbage_collect.go
  states/inspect_primary_key.go
  states/repair_segment.go
  states/show_segment.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/S

#71 Improve visit command implementation
  proto/v2.2/datapb/data_coord.pb.go
  proto/v2.2/indexpb/index_coord.pb.go
  proto/v2.2/querypb/query_coord.pb.go
  proto/v2.2/rootcoordpb/root_coord.pb.go
  states/visit.go
  states/visit_datacoord.go
  states/visit_datanode.go
  states/visit_indexcoord.go
  states/visit_indexnode.go
  states/visit_querycoord.go
  states/visit_querynode.go
  states/visit_rootcoord.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/XL

#72 Implement backup v2 to fetch extra meta for milvus
  models/backup_header.go
  states/backup_mock_connect.go
  states/etcd_backup.go
  states/etcd_restore.go
  states/force_release.go
  states/instance.go
  states/metrics.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/XL

#73 Fix load v2 backup mock instance not set
  states/backup_mock_connect.go
Labels: kind/bug, approved, dco-passed, lgtm, size/XS

#74 Fix go-prompt caused bash hijack
  main.go
  states/exit.go
  states/states.go
Labels: kind/bug, approved, dco-passed, lgtm, size/M

#79 Fix pager blocks when quit early
  main.go
Labels: kind/bug, approved, dco-passed, lgtm, size/M

#80 Fix repair checkpoint usage
  states/etcd/repair/checkpoint.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XS

#81 Print drop ts if segment is dropped
  states/etcd/show/segment.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XS

#82 Support BirdWatcher to insepect delta and stat log path for 2.2 pb
  states/etcd/common/segment.go
Labels: approved, dco-passed, lgtm, size/M
