Repository milvus-io/birdwatcher, pull requests merged in 2023-11, with the labels that each got.

#210 Show the number of dropped segments
  states/etcd/show/segment.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XS

#212 [1.0.x] enhance: improve show segment & distribution result output
  .gitignore
  states/distribution.go
  states/etcd/show/segment.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/S

#214 Keep tailing slash for kv operations
  states/kv/kv.go
  states/kv/utils.go
Labels: approved, dco-passed, lgtm, size/M

#216 support storage analysis with statistics (#215)
  states/etcd/show/segment.go
Labels: approved, dco-passed, lgtm, size/S

#217 Add Current index version for segment-index
  proto/v2.2/index_coord.proto
  proto/v2.2/indexpb/index_coord.pb.go
  states/etcd/show/index.go
  states/etcd/show/segment_index.go
Labels: approved, dco-passed, lgtm, size/XL

#218 Add IndexCurrentVersion and SegmentLevel output
  models/segment.go
  models/segment_state.go
  proto/v2.2/common.proto
  proto/v2.2/commonpb/common.pb.go
  proto/v2.2/data_coord.proto
  proto/v2.2/datapb/data_coord.pb.go
  proto/v2.2/feder.proto
  proto/v2.2/federpb/feder.pb.go
  proto/v2.2/index_cgo_msg.proto
  proto/v2.2/index_coord.proto
  proto/v2.2/indexpb/index_coord.pb.go
  proto/v2.2/internal.proto
  proto/v2.2/internalpb/internal.pb.go
  proto/v2.2/milvus.proto
  proto/v2.2/milvuspb/milvus.pb.go
  proto/v2.2/msg.proto
  proto/v2.2/msgpb/msg.pb.go
  proto/v2.2/plan.proto
  proto/v2.2/proxypb/proxy.pb.go
  proto/v2.2/query_coord.proto
  proto/v2.2/querypb/query_coord.pb.go
  proto/v2.2/rootcoordpb/root_coord.pb.go
  proto/v2.2/schema.proto
  proto/v2.2/schemapb/schema.pb.go
  proto/v2.2/segcore.proto
  states/etcd/common/channel.go
  states/etcd/show/segment.go
  states/etcd/show/segment_index.go
  states/probe.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XXL

#219 Add create timestamp output for show alias
  states/etcd/show/alias.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XS
