Repository milvus-io/birdwatcher, pull requests merged in 2023-01, with the labels that each got.

#83 Change remove-segment-by-id to remove segment
  states/etcd/commands.go
  states/etcd/common/segment.go
  states/etcd/remove/segment.go
  states/etcd/repair/segment_empty.go
  states/etcd/show/segment.go
  states/instance.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#85 support show segment according to target state #84
  states/etcd/show/segment.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XS

#88 Add remove orphan watch channel command
  .dockerignore
  states/backup_mock_connect.go
  states/etcd/commands.go
  states/etcd/common/channel.go
  states/etcd/common/collection.go
  states/etcd/common/list.go
  states/etcd/remove/channel.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#89 Fix remove channel and add more log
  states/etcd/remove/channel.go
Labels: kind/bug, approved, dco-passed, lgtm, size/S

#87 Update backup command
  README.md
Labels: approved, dco-passed, lgtm, size/XS

#86 Print binlog field size in statistics mode
  states/etcd/commands.go
  states/etcd/show/segment.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/S

#90 Add show collection-history command
  states/etcd/commands.go
  states/etcd/common/collection.go
  states/etcd/common/collection_history.go
  states/etcd/common/list.go
  states/etcd/show/collection_history.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L
