Repository milvus-io/birdwatcher, pull requests merged in 2023-06, with the labels that each got.

#148 Adapt database in GetCollectionByID logic
  states/etcd/common/collection.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/S

#150 Accelerate backup command by batch read etcd meta
  states/etcd_backup.go
  states/etcd_restore.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/M

#151 Add verify-segment command
  .gitignore
  states/etcd/common/collection.go
  states/etcd/common/segment.go
  states/instance.go
  states/verify_segment.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#152 Add show partition command
  models/partition.go
  states/etcd/commands.go
  states/etcd/common/partition.go
  states/etcd/show/partition.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#155 Fix all GetCollectionByID usage
  states/download_pk.go
  states/etcd/common/channel.go
  states/etcd/common/collection.go
  states/etcd/repair/channel.go
  states/etcd/repair/checkpoint.go
  states/etcd/repair/segment.go
  states/etcd/show/checkpoint.go
  states/force_release.go
  states/inspect_primary_key.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#156 Add web command
  go.mod
  go.sum
  states/instance.go
  states/visit_rootcoord.go
  states/web.go
Labels: approved, dco-passed, lgtm, size/L

#158 Reset Raw mode before start command running
  bapps/go_prompt.go
  bapps/go_prompt_parser.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/M

#159 Add Collection create time in show collection result
  bapps/go_prompt_parser.go
  states/etcd/show/collection.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XS

#160 Add dbid param for show collection cmd
  models/collection.go
  states/etcd/show/collection.go
Labels: kind/improvement, approved, dco-passed, size/S
