Repository milvus-io/birdwatcher, pull requests merged in 2023-08, with the labels that each got.

#174 Bump version to v1.0.2
  common/version.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XS

#176 Support sub states logic for application
  bapps/app.go
  bapps/go_prompt.go
  bapps/olc.go
  bapps/promptui.go
  bapps/webserver.go
  common/errors.go
  common/version.go
  configs/config.go
  framework/command.go
  framework/state.go
  states/app_control.go
  states/app_state.go
  states/autocomplete/auto_complete.go
  states/autocomplete/auto_complete_file.go
  states/backup_mock_connect.go
  states/disconnected.go
  states/etcd/show/collection.go
  states/etcd_connect.go
  states/exit.go
  states/instance.go
  states/load_backup.go
  states/open.go
  states/parse_file.go
  states/pulsarctl_connect.go
  states/start.go
  states/storage/fs.go
  states/storage/minio.go
  states/util.go
  states/visit.go
  states/visit_datacoord.go
  states/visit_datanode.go
  states/visit_indexcoord.go
  states/visit_indexnode.go
  states/visit_querycoord.go
  states/visit_querynode.go
  states/visit_rootcoord.go
  states/web.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/XXL

#177 Fix ApplicationState sub state transfer
  framework/state.go
  states/app_state.go
  states/balance_explain.go
  states/configuration.go
  states/current_version.go
  states/distribution.go
  states/etcd_backup.go
  states/instance.go
  states/management.go
  states/probe.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#178 Upgrade keyring to fix Mac warning
  go.mod
  go.sum
Labels: kind/improvement, approved, dco-passed, lgtm, size/S

#179 Firx one-line-command broken after AppplicationState refactoring
  bapps/go_prompt.go
  bapps/olc.go
  configs/config.go
  states/app_state.go
Labels: kind/bug, approved, dco-passed, lgtm, size/S

#181 Fix audit log file permission and use date suffix in name
  states/instance.go
Labels: kind/bug, approved, dco-passed, lgtm, size/XS

#182 Fix multi generation cmd logic error
  framework/state.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XS

#183 Add storage-analysis command
  models/fs_stat.go
  states/app_state.go
  states/segment_anaylsis.go
  states/storage/minio.go
  states/storage/ops.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/L

#185 Update the installation comment
  README.md
Labels: kind/improvement, ci-passed, approved, dco-passed, lgtm, size/S

#184 Add FieldID in show index output
  states/etcd/show/index.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XS

#186 Add command for auto fetch goroutine pprof
  states/pprof.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/M

#188 [CP 1.0.x] Add command for auto fetch goroutine pprof (#186)
  states/pprof.go
Labels: kind/enhancement, approved, lgtm, size/M

#189 Fix mergify DCO rule for all branches
  .github/mergify.yml
Labels: kind/improvement, approved, dco-passed, lgtm, size/XS

#190 Fix embedEtcdState command missing
  .gitignore
  states/app_state.go
  states/backup_mock_connect.go
  states/etcd/show/collection_loaded.go
  states/etcd/show/index.go
Labels: kind/bug, approved, dco-passed, lgtm, size/S

#191 [CP 1.0.x] Fix audit log file permission and use date suffix in name (#181)
  states/instance.go
Labels: kind/bug, approved, dco-passed, lgtm, size/XS

#192 Cherry-pick command improvement and bump version to v1.0.3
  common/version.go
  states/etcd/show/collection_loaded.go
  states/etcd/show/index.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/S

#193 Fix dco-pass rule in mergify check for v1.0.x branch
  .github/mergify.yml
Labels: kind/improvement, approved, dco-passed, lgtm, size/XS

#194 Suppport connect to ETCD with tls cerificate
  states/etcd_connect.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/M

#197 Suppport connect to ETCD with tls cerificate
  states/etcd_connect.go
Labels: approved, dco-passed, lgtm, size/M
