Repository milvus-io/birdwatcher, pull requests merged in 2023-02, with the labels that each got.

#91 Adapt v2.2 Replica information format
  models/replica.go
  states/etcd/common/replica.go
  states/etcd/show/replica.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#94 Add VHS generated gif for doc
  README.md
  docs/images/backup.gif
  docs/images/connect.gif
  docs/images/show.gif
  docs/vhs/backup_simple.tape
  docs/vhs/connect.tape
  docs/vhs/show.tape
  states/etcd/remove/channel.go
Labels: kind/documentation, kind/improvement, approved, dco-passed, lgtm, size/M

#97 CI: Add goreleaser for release
  .github/workflows/release.yaml
  .gitignore
  .goreleaser-darwin.yaml
  .goreleaser-linux.yaml
  .goreleaser-release.yaml
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#99 Add rootPath check for connect etcd command
  states/etcd/audit/audit_write.go
  states/etcd_connect.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/M

#100 Add Dockerfile for birdwatcher
  Dockerfile
Labels: kind/improvement, approved, dco-passed, lgtm, size/S
