Repository milvus-io/birdwatcher, pull requests merged in 2023-12, with the labels that each got.

#222 Add remove leaked collection meta cmd
  states/etcd/commands.go
  states/etcd/common/collection.go
  states/etcd/common/segment.go
  states/etcd/remove/collection_clean.go
  states/kv/kv.go
  states/kv/kv_audit.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#223 [CP 1.0.x] Add remove leaked collection meta cmd
  states/etcd/commands.go
  states/etcd/common/collection.go
  states/etcd/common/segment.go
  states/etcd/remove/collection_clean.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#220 allow deletion of non-exist key
  states/kv/kv.go
  states/kv/kv_audit.go
  states/kv/kv_test.go
Labels: dco-passed, lgtm, size/S

#225 Fix gen proto script for proto/v2.2 pkg
  proto/v2.2/datapb/data_coord.pb.go
  proto/v2.2/gen_proto.sh
  proto/v2.2/indexpb/index_coord.pb.go
  proto/v2.2/milvuspb/milvus.pb.go
  proto/v2.2/querypb/query_coord.pb.go
  proto/v2.2/rootcoordpb/root_coord.pb.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XXL

#227 chore(image): add custom tags for manual trigger
  .github/workflows/build-and-push.yaml
Labels: approved, dco-passed, lgtm, size/S

#229 fix clean collection meta command
  states/etcd/remove/collection_dropping.go
  states/kv/kv_audit.go
Labels: approved, dco-passed, lgtm, size/M

#231 Add segment,field level binlog size summary
  states/etcd/show/segment.go
Labels: approved, dco-passed, lgtm, size/XS

#228 Add checker activation
  proto/v2.2/milvuspb/milvus.pb.go
  proto/v2.2/proxypb/proxy.pb.go
  proto/v2.2/query_coord.proto
  proto/v2.2/querypb/query_coord.pb.go
  proto/v2.2/rootcoordpb/root_coord.pb.go
  proto/v2.2/schemapb/schema.pb.go
  states/visit_querycoord.go
  states/visit_querynode.go
Labels: approved, dco-passed, lgtm, size/XXL

#232 Add prefix param for show configuration command
  states/visit.go
Labels: approved, dco-passed, lgtm, size/S
