Repository milvus-io/birdwatcher, pull requests merged in 2023-10, with the labels that each got.

#205 fix wrong operation for getCollectionBy State
  states/etcd/show/collection.go
Labels: approved, dco-passed, lgtm, size/XS

#206 Fix collection history not found for collection with database prefix
  states/etcd/common/collection_history.go
  states/etcd/show/collection_history.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/M

#207 Add `show user` command
  models/user.go
  states/etcd/common/list.go
  states/etcd/common/user.go
  states/etcd/show/user.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L
