Repository milvus-io/birdwatcher, pull requests merged in 2023-04, with the labels that each got.

#137 Make force-release work with qcv2 meta
  states/force_release.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/S

#139 Add command to remove dropping/dropped collection meta
  models/collection.go
  states/etcd/commands.go
  states/etcd/remove/collection_dropping.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#140 Add probe pk command
  states/probe.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#142 Drop segments that collection has been dropped
  states/etcd/commands.go
  states/etcd/remove/segment_collection_dropped.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/M

#144 Add logs and bw_config into gitignore
  .gitignore
Labels: approved, dco-passed, lgtm, size/XS

#143 Add show/set etcd-confg commands
  states/etcd/commands.go
  states/etcd/common/config_etcd.go
  states/etcd/set/etcd_config.go
  states/etcd/show/config_etcd.go
  states/instance.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/L
