Repository milvus-io/birdwatcher, pull requests merged in 2023-07, with the labels that each got.

#161 Refactor command registration logic
  states/backup_mock_connect.go
  states/configuration.go
  states/current_version.go
  states/download_segment.go
  states/etcd_connect.go
  states/exit.go
  states/instance.go
  states/load_backup.go
  states/open.go
  states/parse_file.go
  states/pulsarctl_connect.go
  states/start.go
  states/states.go
  states/util.go
  states/visit_datacoord.go
  states/visit_datanode.go
  states/visit_indexcoord.go
  states/visit_indexnode.go
  states/visit_querycoord.go
  states/visit_querynode.go
  states/visit_rootcoord.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/XXL

#162 Fix missing disconnect file
  states/disconnected.go
Labels: kind/bug, approved, dco-passed, lgtm, size/M

#163 Add remove segment-orphan command
  framework/param.go
  states/backup_mock_connect.go
  states/configuration.go
  states/current_version.go
  states/etcd/commands.go
  states/etcd/common/collection.go
  states/etcd/common/index.go
  states/etcd/common/replica.go
  states/etcd/common/segment.go
  states/etcd/remove/component.go
  states/etcd/remove/segment_orphan.go
  states/etcd/repair/segment.go
  states/etcd/show/channel_watched.go
  states/etcd/show/checkpoint.go
  states/etcd/show/collection.go
  states/etcd/show/collection_history.go
  states/etcd/show/collection_loaded.go
  states/etcd/show/component.go
  states/etcd/show/config_etcd.go
  states/etcd/show/database.go
  states/etcd/show/index.go
  states/etcd/show/partition.go
  states/etcd/show/replica.go
  states/etcd/show/segment.go
  states/etcd/show/segment_index.go
  states/etcd/show/session.go
  states/etcd_connect.go
  states/exit.go
  states/instance.go
  states/load_backup.go
  states/open.go
  states/parse_file.go
  states/pulsarctl_connect.go
  states/states.go
  states/util.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/XXL

#164 Support probing diskann
  states/probe.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/S

#166 Add Collection State filter option
  states/etcd/show/collection.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XS

#167 Add show alias command
  models/alias.go
  states/etcd/common/alias.go
  states/etcd/show/alias.go
  states/etcd/show/partition.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#131 Repair metric_type is in TypeParams instead of IndexParams
  states/etcd/commands.go
  states/etcd/repair/index_metric.go
Labels: kind/bug, approved, dco-passed, lgtm, size/L

#169 Add web server & auto handler parser for show commands
  bapps/webserver.go
  framework/resultset.go
  main.go
  models/channel_watch.go
  models/data_type.go
  models/segment.go
  states/configuration.go
  states/current_version.go
  states/etcd/show/alias.go
  states/etcd/show/channel_watched.go
  states/etcd/show/checkpoint.go
  states/etcd/show/collection.go
  states/etcd/show/collection_history.go
  states/etcd/show/collection_loaded.go
  states/etcd/show/database.go
  states/etcd/show/partition.go
  states/etcd/show/replica.go
  states/etcd/show/session.go
  states/exit.go
  states/instance.go
  states/states.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/XL

#170 supporting balance explian function
  states/balance_explain.go
  states/constants.go
  states/distribution.go
  states/instance.go
  states/util.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/L

#172 fix possible panic when explaining
  states/balance_explain.go
Labels: kind/bug, approved, dco-passed, lgtm, size/S

#173 Add 'not supported' warning for legacy show segment-loaded command
  states/etcd/commands.go
  states/etcd/show/alias.go
  states/etcd/show/segment_loaded.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/M

#171 Add listen events command
  eventlog/event_log.pb.go
  eventlog/event_log.proto
  eventlog/listener.go
  go.mod
  models/session.go
  states/configuration.go
  states/frame_screen.go
  states/management.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/XL
