Repository milvus-io/birdwatcher, pull requests merged in 2023-03, with the labels that each got.

#102 Remove false alarm error message for load-backup
  go.mod
  go.sum
  states/backup_mock_connect.go
  states/errors.go
  states/load_backup.go
  states/open.go
Labels: kind/bug, approved, dco-passed, lgtm, size/L

#106 Add probe command for query function
  models/collection.go
  models/collection_schema.go
  proto/v2.2/planpb/plan.pb.go
  states/instance.go
  states/probe.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XXL

#107 Fix hnsw probe search request ef param type
  states/probe.go
Labels: kind/bug, approved, dco-passed, lgtm, size/XS

#104 Add remove binlog file cmd
  states/etcd/commands.go
  states/etcd/remove/binlog.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L

#109 Fix audit log write panic
  states/etcd/audit/audit_write.go
Labels: kind/bug, approved, dco-passed, lgtm, size/XS

#110 Print segment-index serialized size
  states/etcd/show/segment_index.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XS

#114 Print show collection, collection-loaded result number
  states/etcd/common/collection_loaded.go
  states/etcd/show/collection.go
  states/etcd/show/collection_loaded.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/M

#112 Fix dry mode rootPath check and add force flag
  states/etcd_connect.go
Labels: kind/bug, approved, dco-passed, lgtm, size/M

#115 Make suggestion result stable
  main.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XS

#120 Add show collection by name
  states/etcd/show/collection.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/S

#123 Fix show collection format bug
  states/etcd/show/collection.go
Labels: kind/bug, approved, dco-passed, lgtm, size/XS

#117 Add indexfile process commands
  states/autocomplete/auto_complete.go
  states/autocomplete/auto_complete_file.go
  states/load_backup.go
  states/parse_file.go
  states/start.go
  storage/event_reader.go
  storage/index_reader.go
  storage/payload_reader.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/L

#128 Add version flags and command
  common/version.go
  go.mod
  go.sum
  main.go
  states/util.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/M

#129 Add short description for cmd in backup mode
  states/etcd/commands.go
  states/etcd/remove/channel.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XS

#130 Fix bug for metric_type is in TypeParams when probing
  states/probe.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XS

#132 Add command file history and reverse list feature(Ctrl+R)
  .gitignore
  history/history.go
  main.go
  states/backup_mock_connect.go
  states/etcd_connect.go
  states/exit.go
  states/instance.go
  states/load_backup.go
  states/open.go
  states/start.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/L

#133 Add BApp abstraction for go-prompt and promptui
  bapps/app.go
  bapps/go_prompt.go
  bapps/promptui.go
  history/history.go
  main.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/XL

#134 Add one-line-command feature and show configurations command
  bapps/olc.go
  main.go
  states/configuration.go
  states/distribution.go
  states/etcd/common/pair.go
  states/instance.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/L

#135 Support show segment distribution by collection
  states/distribution.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/S
