Repository milvus-io/birdwatcher, pull requests merged in 2023-09, with the labels that each got.

#199 Fix partition filter not working for `show segment`
  states/etcd/show/partition.go
  states/etcd/show/segment.go
Labels: kind/improvement, ci-passed, approved, dco-passed, lgtm, size/XS

#200 Fix mergify rules not using regex
  .github/mergify.yml
Labels: kind/improvement, approved, dco-passed, lgtm, size/XS

#203 Support remove one binlog from field binlogs (#202)
  states/etcd/remove/binlog.go
Labels: kind/improvement, approved, dco-passed, lgtm, size/L
