Repository milvus-io/birdwatcher, pull requests merged in 2024-10, with the labels that each got.

#319 enhance: Refine `show segment-loaded-grpc` command
  states/balance_explain.go
  states/configuration.go
  states/distribution.go
  states/etcd/common/session.go
  states/etcd/download/distribution.go
  states/etcd/remove/session.go
  states/etcd/repair/channel.go
  states/etcd/repair/manual_compaction.go
  states/etcd/show/legacy_qc_cluster.go
  states/etcd/show/session.go
  states/etcd_backup.go
  states/healthz.go
  states/instance.go
  states/management.go
  states/metrics.go
  states/minio.go
  states/pprof.go
  states/probe.go
  states/update_log_level.go
  states/util.go
  states/visit.go
Labels: approved, dco-passed, lgtm, size/L

#320 enhance: enable check_qn_collection_leak
  models/metrics_info.go
  models/quota_metrics.go
  models/topology.go
  states/etcd/commands.go
  states/etcd/repair/check_qn_collection_leak.go
Labels: approved, dco-passed, lgtm, size/XL

#321 doc: Add markdown document for command detection framework
  docs/bw_framework.md
Labels: approved, dco-passed, lgtm, size/M

#322 enhance: Support show bulkinsert command
  proto/v2.2/data_coord.proto
  proto/v2.2/datapb/data_coord.pb.go
  states/etcd/common/bulkinsert.go
  states/etcd/show/bulkinsert.go
Labels: approved, dco-passed, lgtm, size/XXL
