Repository milvus-io/birdwatcher, pull requests merged in 2024-12, with the labels that each got.

#330 enhance: Refine `show replica` output
  states/etcd/show/replica.go
Labels: approved, dco-passed, lgtm, size/M

#331 enhance: Add node filter when show segment loaded via grpc
  states/distribution.go
Labels: approved, dco-passed, lgtm, size/XS

#329 enhance: Support removing import job
  states/etcd/commands.go
  states/etcd/common/bulkinsert.go
  states/etcd/remove/bulkinsert.go
  states/etcd/show/bulkinsert.go
Labels: approved, dco-passed, lgtm, size/L

#333 enhance: Add delta entry number statistics for segment output
  states/etcd/show/segment.go
Labels: approved, dco-passed, lgtm, size/S
