Repository milvus-io/birdwatcher, pull requests merged in 2024-09, with the labels that each got.

#307 enhance: ignore the case of the input filter parameter
  states/configuration.go
Labels: approved, dco-passed, lgtm, size/XS

#308 enhance: Add `Run` flag for remove compaction command
  states/etcd/commands.go
  states/etcd/remove/compaction_task.go
Labels: approved, dco-passed, lgtm, size/M

#309 fix: Upgrade golangci-lint workflow go version to v1.21
  .github/workflows/golangci-lint.yml
  states/etcd/repair/channel_watched.go
Labels: approved, dco-passed, lgtm, size/XS

#310 enhance: Add flag to control skip bucket exist check
  oss/minio.go
  states/binlog.go
  states/check_partition_key.go
  states/download_pk.go
  states/download_segment.go
  states/inspect_primary_key.go
  states/minio.go
  states/scan_binlog.go
Labels: approved, dco-passed, lgtm, size/M

#311 enhance: Apply deltalog when scanning binlog
  states/scan_binlog.go
Labels: approved, dco-passed, lgtm, size/M

#312 Add IsSorted field for segment
  models/segment.go
  proto/v2.2/data_coord.proto
  proto/v2.2/datapb/data_coord.pb.go
  states/etcd/show/segment.go
Labels: approved, dco-passed, lgtm, size/XL

#313 support batch remove segment meta with filters
  go.mod
  states/etcd/common/segment.go
  states/etcd/remove/collection_clean.go
  states/etcd/remove/segment.go
Labels: approved, dco-passed, lgtm, size/L

#315 fix: Remove unused Unsafe reflection code
  bapps/go_prompt.go
  bapps/go_prompt_parser.go
  go.mod
  go.sum
Labels: approved, dco-passed, lgtm, size/L

#316 fix: [Cherry-pick] Remove unused Unsafe reflection code (#315)
  bapps/go_prompt.go
  bapps/go_prompt_parser.go
Labels: approved, dco-passed, lgtm, size/S

#317 enhance: Rename duplicated compaction task command
  go.mod
  states/etcd/remove/compaction_task.go
Labels: approved, dco-passed, size/XS
