Repository milvus-io/birdwatcher, pull requests merged in 2024-08, with the labels that each got.

#287 enhance: Refine inspect-pk command to support remote mode
  states/backup_mock_connect.go
  states/current_version.go
  states/download_pk.go
  states/download_segment.go
  states/inspect_primary_key.go
  states/instance.go
  storage/binlog_reader.go
  storage/index_reader.go
Labels: approved, dco-passed, lgtm, size/XL

#288 Add block & mutex pprof type support
  states/pprof.go
Labels: approved, dco-passed, lgtm, size/XS

#289 Add compact cmd in visit_datacoord
  go.mod
  go.sum
  states/visit.go
  states/visit_datacoord.go
Labels: approved, dco-passed, lgtm, size/M

#292 refine show segment ouputs
  states/etcd/show/segment.go
Labels: approved, dco-passed, lgtm, size/L

#291 enhance: Add `remove session` command
  models/session.go
  states/etcd/common/session.go
  states/etcd/remove/session.go
Labels: approved, dco-passed, lgtm, size/M

#290 enhance: Support show database filter with dbid
  states/etcd/show/database.go
Labels: approved, dco-passed, lgtm, size/XS

#297 use the env config to replace the default value when connecting the etcd
  states/etcd_connect.go
Labels: approved, dco-passed, lgtm, size/S

#293 enhance: Support scan-binlog command
  bapps/webserver.go
  go.mod
  go.sum
  states/scan_binlog.go
  states/states.go
Labels: approved, dco-passed, lgtm, size/L

#296 enhance: Support filter `show segment-index` result with field ID
  states/etcd/show/segment_index.go
Labels: approved, dco-passed, lgtm, size/M

#299 enhance: Enable to show database props
  models/database.go
  states/etcd/show/database.go
Labels: approved, dco-passed, lgtm, size/S

#300 enhance: Print Array field element type
  models/collection.go
  models/collection_schema.go
  states/etcd/show/collection.go
Labels: approved, dco-passed, lgtm, size/M

#298 feature: Enable to remove checkpoints when remove orphan channel
  states/etcd/common/channel.go
  states/etcd/remove/channel.go
Labels: approved, dco-passed, lgtm, size/M

#301 enhance: Support aliyun as oss source
  go.mod
  go.sum
  oss/aliyun.go
  oss/minio.go
  oss/tencent.go
  states/minio.go
Labels: approved, dco-passed, lgtm, size/L

#302 enhance: Support Tencent myqcloud as OSS source
  oss/minio.go
  oss/tencent.go
  states/scan_binlog.go
Labels: approved, dco-passed, lgtm, size/S

#304 enhance: print schema info in show channel-watched
  models/channel_watch.go
  states/etcd/common/channel.go
  states/etcd/show/channel_watched.go
Labels: approved, dco-passed, lgtm, size/M

#305 enhance: Support `repair channel-watch` command to set empty schema
  models/channel_watch.go
  models/collection.go
  states/backup_mock_connect.go
  states/etcd/common/channel.go
  states/etcd/common/channel_watch.go
  states/etcd/common/collection.go
  states/etcd/common/list.go
  states/etcd/repair/channel_watched.go
  states/etcd/restore/collection.go
  states/etcd/show/channel_watched.go
Labels: approved, dco-passed, lgtm, size/L

#306 enhance: Add schema flags for channel watch command
  states/etcd/show/channel_watched.go
Labels: approved, dco-passed, lgtm, size/M
