Repository milvus-io/birdwatcher, pull requests merged in 2024-02, with the labels that each got.

#240 fix: Show segment-index of segments in Flushing state
  states/etcd/show/segment_index.go
Labels: approved, dco-passed, lgtm, size/XS

#241 Add index params with kv pair
  states/etcd/commands.go
  states/etcd/repair/add_index_param_retrive_friendly.go
Labels: approved, dco-passed, lgtm, size/L

#242 Refine code
  states/etcd/repair/add_index_param_retrive_friendly.go
Labels: approved, dco-passed, lgtm, size/S, do-not-merge/hold

#243 fix lint
  states/etcd/repair/add_index_param_retrive_friendly.go
Labels: approved, dco-passed, lgtm, size/XS

#244 enhance: Add healthz-check command
  framework/resultset.go
  states/healthz.go
Labels: approved, dco-passed, lgtm, size/L

#245 fix: Get growing segment id when growing info is in GrowingSegments
  states/distribution.go
Labels: approved, dco-passed, lgtm, size/XS

#246 add download global-distribution command
  states/etcd/commands.go
  states/etcd/download/distribution.go
  states/instance.go
Labels: approved, dco-passed, lgtm, size/L

#247 enhance: Add check-partition-key command to export partition key error data
  go.mod
  states/binlog.go
  states/check_partition_key.go
  states/download_segment.go
  states/etcd/common/segment.go
  states/hash.go
  states/inspect_primary_key.go
  states/minio.go
  storage/binlog_reader.go
  storage/binlog_reader_test.go
  storage/delta_data.go
  storage/deltalog_reader.go
  storage/index_reader.go
  storage/parquet_reader.go
  storage/parquet_writer.go
  storage/payload_reader.go
  storage/primary_key.go
  storage/primary_keys.go
Labels: approved, dco-passed, lgtm, size/XXL

#248 enhance: Unify oss access in oss package & support gcp
  go.mod
  go.sum
  oss/gcp.go
  oss/minio.go
  states/minio.go
Labels: approved, dco-passed, lgtm, size/L
