Repository milvus-io/birdwatcher, pull requests merged in 2024-05, with the labels that each got.

#256 enhance: Add `partition-loaded` and make `force-release` selectable
  models/collection_loaded.go
  models/partition_loaded.go
  states/backup_mock_connect.go
  states/etcd/audit/audit.go
  states/etcd/common/collection.go
  states/etcd/common/collection_loaded.go
  states/etcd/common/partition_loaded.go
  states/etcd/show/checkpoint.go
  states/etcd/show/collection.go
  states/etcd/show/collection_loaded.go
  states/etcd/show/index.go
  states/etcd/show/partition_loaded.go
  states/force_release.go
  states/instance.go
Labels: approved, dco-passed, lgtm, size/L

#257 enhance: Add `force` flag for `remove channel` command
  states/etcd/remove/channel.go
Labels: approved, dco-passed, lgtm, size/S

#259 enhance: Print segment stats/deltalog size aggregration
  states/etcd/show/segment.go
Labels: approved, dco-passed, lgtm, size/XS

#258 enhance: Support `consume` command with Kafka MQ
  .golangci.yml
  mq/factory.go
  mq/factory_wkafka.go
  mq/ifc/msgstream.go
  mq/kafka/kafka.go
  mq/kafka/kafka_id.go
  mq/kafka/kafka_test.go
  mq/pulsar/pulsar_id.go
  mq/pulsar/puslar.go
  states/consume.go
Labels: approved, dco-passed, lgtm, size/L

#260 enhance: Bump v1.0.4
  common/version.go
  mq/msg.go
Labels: approved, dco-passed, size/XS

#262 enhance: Refine history suggestion when input contains spaces
  bapps/go_prompt.go
Labels: approved, dco-passed, lgtm, size/XS

#263 enhance: Add setup workspace step to enable history by default
  configs/config.go
Labels: approved, dco-passed, lgtm, size/S

#265 enhance: Show segment's Memory Size
  models/segment.go
  proto/v2.2/common.proto
  proto/v2.2/commonpb/common.pb.go
  proto/v2.2/data_coord.proto
  proto/v2.2/datapb/data_coord.pb.go
  proto/v2.2/etcd_meta.proto
  proto/v2.2/etcdpb/etcd_meta.pb.go
  proto/v2.2/gen_proto.sh
  proto/v2.2/index_coord.proto
  proto/v2.2/indexpb/index_coord.pb.go
  proto/v2.2/internal.proto
  proto/v2.2/internalpb/internal.pb.go
  proto/v2.2/milvus.proto
  proto/v2.2/milvuspb/milvus.pb.go
  proto/v2.2/plan.proto
  proto/v2.2/proxy.proto
  proto/v2.2/proxypb/proxy.pb.go
  proto/v2.2/query_coord.proto
  proto/v2.2/querypb/query_coord.pb.go
  proto/v2.2/rg.proto
  proto/v2.2/rgpb/rg.pb.go
  proto/v2.2/root_coord.proto
  proto/v2.2/rootcoordpb/root_coord.pb.go
  proto/v2.2/schema.proto
  proto/v2.2/schemapb/schema.pb.go
  proto/v2.2/segcore.proto
  states/etcd/show/segment.go
Labels: approved, dco-passed, lgtm, size/XXL
