Repository milvus-io/birdwatcher, pull requests merged in 2024-06, with the labels that each got.

#269 enhance: manual compaction trigger
  states/etcd/commands.go
  states/etcd/repair/manual_compaction.go
Labels: approved, dco-passed, lgtm, size/M

#267 enhance: Support filter segment with segment level
  states/etcd/show/segment.go
Labels: approved, dco-passed, lgtm, size/XS

#270 enhance: Add `repair legacy-collection-remnant` command
  states/etcd/commands.go
  states/etcd/repair/collection_legacy.go
  states/etcd/repair/component.go
  states/instance.go
Labels: approved, needs-dco, lgtm, size/M

#271 enhance: Add auto detect rootPath for connect command
  states/etcd_connect.go
Labels: approved, dco-passed, lgtm, size/S

#272 fix: Remove collection history item when repairing legacy collection
  states/etcd/common/collection_history.go
  states/etcd/repair/collection_legacy.go
  states/etcd/show/collection_history.go
Labels: approved, dco-passed, lgtm, size/M

#273 enhance: Show mem size in statistics
  states/etcd/show/segment.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/M

#274 enhance: Use auto oss access detection for download-segment
  states/download_segment.go
  states/instance.go
  states/minio.go
Labels: approved, dco-passed, lgtm, size/L

#266 enhance: Show log id
  models/segment.go
  states/etcd/show/segment.go
Labels: kind/enhancement, approved, dco-passed, lgtm, size/S

#277 enhance:add support for partition stats for major compaction test(#276)
  models/segment.go
  models/segment_state.go
  states/etcd/show/segment.go
Labels: approved, dco-passed, lgtm, size/S

#278 Bump birdwatcher to v1.0.5
  common/version.go
Labels: approved, dco-passed, size/XS

#279 fix: Add ruleguard dependency
  go.mod
  go.sum
Labels: approved, dco-passed, lgtm, size/XS
