Repository milvus-io/birdwatcher, pull requests merged in 2024-07, with the labels that each got.

#280 enhance: Filter `show database` result by name
  states/etcd/common/database.go
  states/etcd/show/database.go
Labels: approved, dco-passed, lgtm, size/S

#281 enhance: Support `show resource-group` command
  models/database.go
  models/resource_group.go
  states/etcd/common/replica.go
  states/etcd/common/resource_group.go
  states/etcd/show/resource_group.go
Labels: approved, dco-passed, lgtm, size/L

#282 Fixbug: filter by planID is not working
  states/etcd/show/compaction.go
Labels: approved, dco-passed, lgtm, size/S

#283 feat: Add remove compaction command
  states/etcd/commands.go
  states/etcd/remove/compaction_task.go
  states/etcd/show/compaction.go
Labels: approved, dco-passed, lgtm, size/M

#284 Experiment: add alter field to change is_clustering_key
  states/etcd/commands.go
  states/etcd/common/collection.go
  states/etcd/set/collection_alter.go
  states/etcd/show/compaction.go
Labels: approved, dco-passed, lgtm, size/L

#285 enhance: Display collection clustering key info
  models/collection.go
  models/collection_schema.go
  states/etcd/show/collection.go
Labels: approved, dco-passed, lgtm, size/S

#286 Fix failed to alter field schema
  states/etcd/common/collection.go
Labels: approved, dco-passed, lgtm, size/M
