Repository milvus-io/birdwatcher, pull requests merged in 2025-08, with the labels that each got.

#419 enhance: Bump version to v1.1.0
  common/version.go
Labels: approved, dco-passed, lgtm, size/XS

#420 chore: update dockerfile
  Dockerfile
Labels: approved, dco-passed, lgtm, size/M

#421 enhance: Add healthz check item for missing index
  states/healthz/check_item.go
  states/healthz/loaded_index_missing.go
Labels: approved, dco-passed, lgtm, size/L

#422 enhance: Support print session as json
  states/etcd/show/session.go
Labels: approved, dco-passed, lgtm, size/S
