Repository milvus-io/birdwatcher, pull requests merged in 2025-07, with the labels that each got.

#397 fix: Iterate next rg when RecordReader return EOF
  storage/segment_reader.go
Labels: approved, dco-passed, lgtm, size/M

#402 enhance: Bump minio client to handle tencent oss
  go.mod
  go.sum
Labels: approved, dco-passed, lgtm, size/M

#403 Fix: multi RecordReader offset issue
  storage/binlog/v2/binlog_reader.go
  storage/segment_reader.go
Labels: approved, dco-passed, lgtm, size/S

#405 enhance: Add healthz check items and related commands
  states/etcd/common/collection.go
  states/healthz.go
  states/healthz/check_item.go
  states/healthz/issue_43407.go
  states/healthz/queryview_lag.go
  states/mgrpc/connect.go
Labels: approved, dco-passed, lgtm, size/XL

#409 enhance: add show wal recovery storage tool
  go.mod
  go.sum
  states/etcd/common/wal_recovery_storage.go
  states/etcd/repair/wal_recovery_storage.go
  states/etcd/show/wal_distribution.go
  states/etcd/show/wal_recovery_storage.go
Labels: approved, dco-passed, lgtm, size/XL

#412 enhance: add message id guess tool
  states/etcd/common/wal_recovery_storage.go
  states/wal_message_id.go
Labels: approved, dco-passed, lgtm, size/M

#413 enhance: Rectify entry offset when scanning binlog
  go.mod
  states/scan_binlog.go
  storage/segment_iterator.go
Labels: approved, dco-passed, lgtm, size/S
