Repository milvus-io/birdwatcher, pull requests merged in 2025-02, with the labels that each got.

#346 enhance: Pass ctx for `common.ListSegmentIndex` instead
  states/etcd/common/index.go
  states/etcd/repair/segment.go
  states/etcd/show/segment_index.go
Labels: approved, dco-passed, lgtm, size/S

#353 Fix typo
  states/etcd/show/segment_loaded.go
Labels: approved, dco-passed, lgtm, size/XS

#354 enhance: Upgrade artifacts upload/download action version
  .github/workflows/release.yaml
Labels: approved, dco-passed, lgtm, size/XS

#357 enhance: Sync v1.0.x pr to main branch (part4)
  .goreleaser-darwin.yaml
  .goreleaser-linux.yaml
  Makefile
  cmd/birdwatcher/main.go
  states/backup_mock_connect.go
  states/etcd/common/bulkinsert.go
  states/etcd/common/index.go
  states/etcd/remove/dirty_importing_segment.go
  states/etcd/repair/segment.go
  states/etcd/show/alias.go
  states/etcd/show/bulkinsert.go
  states/etcd/show/channel_watched.go
  states/etcd/show/checkpoint.go
  states/etcd/show/collection.go
  states/etcd/show/collection_history.go
  states/etcd/show/collection_loaded.go
  states/etcd/show/compaction.go
  states/etcd/show/component.go
  states/etcd/show/config_etcd.go
  states/etcd/show/database.go
  states/etcd/show/etcd_kv_tree.go
  states/etcd/show/index.go
  states/etcd/show/partition.go
  states/etcd/show/partition_loaded.go
  states/etcd/show/replica.go
  states/etcd/show/resource_group.go
  states/etcd/show/segment.go
  states/etcd/show/segment_index.go
  states/etcd/show/segment_loaded.go
  states/etcd/show/session.go
  states/etcd_connect.go
  states/instance.go
  states/scan_binlog.go
  states/scan_deltalog.go
  states/visit_querycoord.go
Labels: approved, dco-passed, lgtm, size/XL

#356 enhance: Update goreleaser build main config
  .goreleaser-darwin.yaml
  .goreleaser-linux.yaml
Labels: approved, dco-passed, lgtm, size/XS

#359 enhance: Add `repair index-dup` command
  states/etcd/repair/field_index.go
  states/etcd/repair/index_duplicate.go
Labels: approved, dco-passed, lgtm, size/M

#360 enhance: Fix desc typo lint
  states/etcd/repair/index_duplicate.go
Labels: approved, dco-passed, lgtm, size/XS

#361 enhance: Bump version to v1.0.x
  common/version.go
Labels: approved, dco-passed, lgtm, size/XS

#351 Update README.md
  README.md
Labels: approved, dco-passed, lgtm, size/XS
