Repository milvus-io/birdwatcher, pull requests merged in 2025-01, with the labels that each got.

#334 enhance: Use default etcd port 2379 when port not passed
  states/etcd_connect.go
Labels: approved, dco-passed, lgtm, size/XS

#336 enhance: Support `scan-deltalog` command
  states/scan_binlog.go
  states/scan_deltalog.go
Labels: approved, dco-passed, lgtm, size/L

#335 fix: Fix remove bulkinsert job command
  states/etcd/common/bulkinsert.go
Labels: approved, dco-passed, lgtm, size/S

#337 fix: Separate basePath & metaPath to show config-etcd
  states/backup_mock_connect.go
  states/etcd/show/alias.go
  states/etcd/show/bulkinsert.go
  states/etcd/show/channel_watched.go
  states/etcd/show/checkpoint.go
  states/etcd/show/collection.go
  states/etcd/show/collection_history.go
  states/etcd/show/collection_loaded.go
  states/etcd/show/compaction.go
  states/etcd/show/component.go
  states/etcd/show/config_etcd.go
  states/etcd/show/database.go
  states/etcd/show/index.go
  states/etcd/show/partition.go
  states/etcd/show/partition_loaded.go
  states/etcd/show/replica.go
  states/etcd/show/resource_group.go
  states/etcd/show/segment.go
  states/etcd/show/segment_index.go
  states/etcd/show/segment_loaded.go
  states/etcd/show/session.go
  states/instance.go
Labels: approved, dco-passed, lgtm, size/M

#340 enhance: enable to show etcd kv tree
  states/etcd/show/etcd_kv_tree.go
Labels: approved, dco-passed, lgtm, size/L

#341 enhance: Bump some denpendency version for security issues
  .github/workflows/golangci-lint.yml
  .golangci.yml
  Makefile
  go.mod
  go.sum
  states/parse_file.go
Labels: approved, dco-passed, lgtm, size/XL

#342 enhance: [v1.0.x] Bump dependency version for security issues
  go.mod
  go.sum
Labels: approved, dco-passed, lgtm, size/XL

#343 enhance: Add default $ps & $timestamp env for scan expr
  states/scan_binlog.go
  states/scan_deltalog.go
Labels: approved, dco-passed, lgtm, size/XS

#344 fix: Fix scan-binlog panic
  states/scan_binlog.go
Labels: approved, dco-passed, lgtm, size/XS
